const Map<String, String> arTranslation = {
  "appName": "Nutri Guide",
  "welcome": "مرحبا",
  "welcomeTitle": "مرحبا بكم",
  "welcomeBody": "هنا نقدم لكم ارشادات ونصائح حول الحميات الصحية لمساعدتك في تحقيق أهدافك الصحية.",
  "exit": "خروج",
  "language": "اللغة",
  "splash": "انتظر...",
  "login": "تسجيل الدخول",
  "enterUserName": "ادخل اسم المستخدم",
  "username": "اسم المستخدم",
  "hintPassword": "ادخل كلمة السر",
  "password": "كلمة السر",
  "dont_have_account": " ليس لدي حساب",
  "dontHaveAccountQuestion": "ليس لديك حساب؟ ",
  "createAccountAction": "قم بإنشاء حساب",
  "enterPersonalEmail": "ادخل الايميل الشخصي",
  "alreadyHaveAccountQuestion": "لديك حساب بالفعل ؟ ",
  "loginAction": "قم بتسجيل دخول",
  "asUser": "كمستخدم",
  "asDoctor": "التسجيل كطبيب",
  "permissionRequired": "إذن مطلوب",
  "exactAlarmPermissionDescription": "لضمان رنين التنبيه في الوقت المحدد، نحتاج إلى إذن المنبهات الدقيقة. يرجى تفعيله من الإعدادات.",
  "enterNameShort": "ادخل الإسم",
  "confirmPasswordAction": "قم بتأكيد كلمة السر",
  "enterDietPrice": "ادخل سعر الحمية",
  "enterBankAccount": "ادخل الحساب البنكي",
  "academicDegree": "الدرجة العلمية",
  "cvBio": "السيرة الذاتية",
  "signup": "انشاء حساب",
  "forget_password": "نسيت كلمة السر",
  'forgotPasswordTitle': 'نسيت كلمة المرور',
  'verifyEmailTitle': 'تحقق من الإيميل',
  'verificationCode': 'كود التحقق',
  'verificationCodeSentTo': 'تم إرسال كود التحقق الى',
  'verify': 'تحقق',
  'goBack': 'تراجع',
  'verifyCodeRequired': 'يرجى إدخال كود التحقق',
  'verifyFailed': 'فشل التحقق',
  'emailVerified': 'تم التحقق من البريد الإلكتروني بنجاح',
  'verificationCodeResent': 'تم إعادة إرسال كود التحقق إلى بريدك الإلكتروني',
  'resendCode': 'إعادة إرسال الكود',
  'email': 'البريد الإلكتروني',
  'enterYourEmail': 'أدخل البريد الإلكتروني',
  'sendResetLink': 'إرسال رابط إعادة التعيين',
  'pleaseWait': 'يرجى الانتظار...',
  // signup
  'signupTitle': 'إنشاء حساب',
  'signupButton': 'تسجيل',

  // fields
  'name': 'الاسم',
  'enterName': 'أدخل الاسم',
  'enterEmail': 'أدخل البريد الإلكتروني',
  'phoneOptional': 'رقم الهاتف (اختياري)',
  'enterPhone': 'أدخل رقم الهاتف',

  // role
  'roleOptional': 'الدور (اختياري)',
  'selectRole': 'اختر الدور',
  'patient': 'مريض',
  'doctor': 'طبيب',

  'passwordHint': '8 أحرف على الأقل',
  'confirmPassword': 'تأكيد كلمة المرور',
  'confirmPasswordHint': 'أعد إدخال كلمة المرور',

  "homeTitle": "الصفحة الرئيسية",
  "settings": "الإعدادات",
  "personalAccount": "الحساب الشخصي",
  "remindersAlerts": "تذكيرات ومنبهات",
  "team": "فريق العمل",
  "editProfile": "تعديل الملف الشخصي",
  "enterPassword": "ادخل كلمة السر",
  "addReminder": "إضافة تذكير",
  "reminderTime": "وقت التذكير",
  "save": "حفظ",
  "close": "اغلاق",
  "send": "ارسال",
  "medicalTest": "الفحص الطبي",
  "enterTestName": "ادخل اسم الفحص",
  "selectFile": "يرجى اختيار ملف",
  "tapToUpload": "اضغط للرفع",
  "personalPatientInfo": "معلومات المريض الشخصية",
  "editPersonalInfo": "تعديل البيانات الشخصية",
  "diets": "الحميات",
  "dietsPatientsTitle": "الحميات · المرضى",
  "chat": "الدردشة",
  "chatWithPatients": "الدردشة مع المرضى",
  "reports": "التقارير",
  "bodyCalculations": "حسابات الجسم",
  "specialistDoctorInfo": "معلومات الطبيب المختص",
  "goToYourForums": "الذهاب الى منتداك التغذوي",
  "showBodyCalculations": "عرض حسابات الجسم",
  "saveCalculation": "حفظ الحساب",
  "tapToViewDetails": "اضغط لعرض التفاصيل",
  "calculation": "حساب",
  "noCalculationsYet": "لا توجد حسابات بعد. قم بالحساب من القائمة واحفظه.",
  "totalKcal": "إجمالي السعرات اليومية",
  "medicalExaminations": "الفحوصات الطبية",
  "helpFiles": "ملفات مساعدة",
  "helpFileJurd": "الكتاب الاردني",
  "helpFileKrause": "مرجع كراوس",
  "helpFileAlter": "نظام البدائل",
  "mainMenu": "القائمة الرئيسية",
  "edit": "تعديل",
  "delete": "حذف",
  "noReminders": "لا توجد تذكيرات بعد. اضغط إضافة تذكير لإنشاء واحد.",
  "myClinic": "عيادتي",
  "stepCounter": "عداد الخطوات",
  "startCounting": "بدء العد",
  "step": "خطوة",
  "steps": "خطوات",
  "stepCounterPermissionDenied": "يجب السماح بتتبع النشاط لعد الخطوات",
  "spiritualNutrition": "التغذية الروحية",
  "morningAthkar": "أذكار الصباح",
  "eveningAthkar": "أذكار المساء",
  "athkar": "الأذكار",
  "noAthkarFound": "لا توجد أذكار",
  "comingSoon": "قريباً",
  "tooManyRequests": "طلبات كثيرة. يرجى الانتظار دقيقة والمحاولة مرة أخرى.",
  "download": "تحميل",
  "openFile": "فتح",
  "downloadFailed": "فشل التحميل",
  "downloadFailedTryBrowser": "يمكنك تجربة فتح الرابط في المتصفح:",
  "downloading": "جاري التحميل...",
  "downloadSuccess": "تم التحميل بنجاح",
  "fileDownloadedTo": "تم تنزيل الملف إلى المسار",
  "noHelpFiles": "لا توجد ملفات مساعدة",
  "noMedicalTests": "لا توجد فحوصات طبية",
  "noPatients": "لا يوجد مرضى",
  "selectPatient": "اختر مريضاً لعرض فحوصاته الطبية",
  "doctorsList": "قائمة الأطباء",
  "doctorsListDesc": "تصفح الأطباء المتاحين",
  "tips": "النصائح",
  "tipsDesc": "نصائح وإرشادات صحية",
  "tipsIntro": "العديد من النصائح الطبية التغذوية المفيدة لك!",
  "tipsGeneral": "نصائح تغذوية عامة",
  "tipsSports": "نصائح رياضية",
  "tipsMyths": "خرافات تغذوية",
  "noTipsFound": "لا توجد نصائح",
  "adDetails": "إعلان",
  "adDescription": "الوصف",
  "openLink": "فتح الرابط",
  "callNow": "اتصل",
  "bmiCalc": "حساب BMI",
  "bmiCalcDesc": "احسب مؤشر كتلة الجسم بسرعة",
  "phone": "الهاتف",
  "role": "الدور",
  "logout": "تسجيل الخروج",
  "yourPrivateClinic": "عيادتك الخاصة",
  "welcomeToClinic": "مرحبا بك",
  "welcomeToClinicSub": "في عيادتك الافتراضية",
  "welcomeToDoctorVirtualClinic": "مرحبا بك في عيادة الطبيب @name",
  "patientsList": "قائمة المرضى",
  "searchForPatient": "ابحث عن مريضك",
  "patientInformation": "معلومات المريض",
  "nutritionalCalculations": "الحسابات التغذوية",
  "proteinFatCarbs": "نسبة البروتين والدهون والكربوهيدرات",
  "patientName": "اسم المريض",
  "patientAge": "عمر المريض",
  "patientGender": "جنس المريض",
  "patientPhone": "رقم هاتف المريض",
  "saveChanges": "حفظ التعديل",
  "servingsInGrams": "عدد الحصص بالجرام",
  "macroPercent": "النسبة المئوية",
  "totalCalories": "إجمالي السعرات",
  "macroSumMustBe100": "مجموع النسب يجب أن يساوي 100٪",
  "physicalActivityLevel": "النشاط الحركي",
  "calories": "السعرات الحرارية",
  "bmr": "BMR",
  "noInternet": "لا يوجد اتصال بالإنترنت",
  "serverError": "خطأ في الخادم",
  "retry": "إعادة المحاولة",
  "refresh": "تحديث",
  "noDoctors": "لا يوجد أطباء حالياً",
  "available": "متاح",
  "notAvailable": "غير متاح",
  "verified": "موثّق",
  "notVerified": "غير موثّق",
  "rating": "التقييم",
  "rateDoctor": "قيّم هذا الطبيب",
  "yourRating": "تقييمك",
  "noRateYet": "لم تُقيّم بعد — اضغط على النجوم",
  "noRatesYet": "لا توجد تقييمات بعد",
  "sendRate": "إرسال التقييم",
  "reviews": "تقييم",
  "noReviews": "لا توجد تقييمات بعد",
  "ratingSaved": "تم حفظ التقييم",
  "experience": "الخبرة",
  "years": "سنوات",
  "fee": "الأجرة",
  "heightCm": "الطول (سم)",
  "heightHint": "أدخل الطول بالسنتيمتر",
  "weightKg": "الوزن (كجم)",
  "weightHint": "أدخل الوزن بالكيلوجرام",
  "calculate": "احسب",
  "bmiResult": "مؤشر كتلة الجسم",
  "bmiUnder": "نقص في الوزن",
  "bmiNormal": "وزن طبيعي",
  "bmiOver": "زيادة في الوزن",
  "bmiObese": "سمنة",
  "error": "خطأ",
  "enterHeightWeight": "يرجى إدخال الطول والوزن",
  "invalidValues": "قيم غير صحيحة",
  "invalidAge": "يرجى إدخال عمر منطقي (أقل من 100)",
  "invalidWeight": "يرجى إدخال وزن منطقي (أقل من 200 كغ)",
  "invalidHeight": "يرجى إدخال طول منطقي (بين 50 و 250 سم)",
  "doctorDetails": "تفاصيل الطبيب",
  "personalEmail": "الإيميل الشخصي",
  "bankAccount": "الحساب البنكي",
  "dietPrice": "سعر الحمية",
  "choosePlan": "اختر الخطة",
  "basicPlan": "أساسي",
  "premiumPlan": "مميز",
  "months": "شهر",
  "subscribe": "اشتراك",

  "gender": "الجنس",
  "degree": "المؤهل",
  "specialization": "التخصص",
  "license": "رقم الترخيص",
  "consultationFee": "رسوم الاستشارة",
  "bio": "النبذة التعريفية",
  "yearsOfExperience": "سنوات الخبرة",
  "success": "تم",
  "ok": "موافق",
  "sessionExpired": "انتهت الجلسة، سجل الدخول مرة أخرى",
  "subscribeFailed": "فشل الاشتراك، حاول مرة أخرى",
  "subscriptionCreated": "تم إنشاء الاشتراك بنجاح",
  "subscriptionPending": "اشتراكك بانتظار الموافقة",
  "subscriptionPendingDesc": "تم استلام الفاتورة، سيظهر حقل 'حميتي' هنا فور موافقة الإدارة.",
  "virtual_payment": "الدفع الافتراضي",
  "payment_card": "بطاقة",
  "payment_cash": "نقداً",
  "payment_wallet": "محفظة",
  "summary_plan": "الخطة",
  "summary_duration": "المدة",
  "summary_price": "السعر",
  "pay_and_subscribe": "ادفع واشترك",

  "payment_transfer": "حوالة",

// Card
  "card_info": "بيانات البطاقة",
  "card_holder": "اسم حامل البطاقة",
  "card_holder_hint": "الاسم المكتوب على البطاقة",
  "card_number": "رقم البطاقة",
  "card_number_hint": "**** **** **** ****",
  "card_exp": "تاريخ الانتهاء",
  "card_exp_hint": "MM/YY",
  "card_cvv": "رمز CVV",
  "card_cvv_hint": "***",

// Wallet
  "wallet_info": "بيانات المحفظة",
  "wallet_name": "اسم المحفظة",
  "wallet_name_hint": "مثال: يمن باي",
  "wallet_number": "رقم المحفظة",
  "wallet_number_hint": "رقم الهاتف أو الحساب",
  "wallet_ref": "رقم العملية",
  "wallet_ref_hint": "رقم أو مرجع العملية",

// Transfer
  "transfer_info": "بيانات الحوالة",
  "transfer_sender": "اسم المُرسل",
  "transfer_sender_hint": "اسم الشخص المُرسل",
  "transfer_receiver": "اسم المُستلم",
  "transfer_receiver_hint": "اسم الشخص المُستلم",
  "transfer_ref": "رقم الحوالة",
  "transfer_ref_hint": "رقم أو مرجع الحوالة",
  "transfer_amount": "مبلغ الحوالة",
  "transfer_amount_hint": "أدخل المبلغ",
  "login_failed": "فشل الدخول",
  "accountPendingApproval": "حسابك بانتظار الموافقة من الإدارة.",
  "accountPendingApprovalHint": "التطبيق يسمح للطبيب بالدخول قبل الموافقة. يجب أن يعيد الخادم رمز الدخول (token) لأطباء بانتظار الموافقة (مثلاً عند إرسال allow_pending_doctor: true). اطلب من المسؤول تفعيل ذلك.",
  "male":"ذكر",
  "female":"انثى",
  "results":"النتيجة",
  "age":"العمر",
  // العناوين العامة
  "bmiBmrCalc": "حاسبة الوزن والسعرات العلاجية",
  "enterData": "إدخال البيانات الحيوية",

  "kcalPerDay": "سعرة/يوم",

  // حقول الإدخال

  "ageHint": "مثال: 25",


  // مستويات النشاط (حسب الورقة)
  "activityLevel": "مستوى النشاط البدني",
  "activitySedentary": "خامل (لا يوجد نشاط)",
  "activityLow": "نشاط منخفض",
  "activityModerate": "نشاط متوسط",
  "activityVery": "نشاط عالي جداً",
  "activityExtra": "نشاط رياضي شاق",


  "bmiObese1": "سمنة درجة أولى (Class I)",
  "bmiObese2": "سمنة درجة ثانية (Class II)",
  "bmiObese3": "سمنة مفرطة (Class III)",

  "enterAllFields": "يرجى إدخال جميع البيانات",


  "completeProfile": "أكمل بياناتك",

  "dateOfBirth": "تاريخ الميلاد",

  "physicalActivity": "النشاط البدني",
  "sedentary": "خامل",
  "low": "نشاط منخفض",
  "active": "نشاط متوسط",
  "veryActive": "نشاط عالي",
  "medicalHistory": "التاريخ المرضي",
  "profileSaved": "تم حفظ البيانات بنجاح",
  "fillFields": "يرجى تعبئة الحقول المطلوبة بشكل صحيح",

  // forums
  "forums": "المنتديات",
  "forumsDesc": "شارك في النقاشات مع الآخرين",
  "noForums": "لا توجد منتديات حالياً",
  "forumPosts": "المنشورات",
  "noPosts": "لا توجد منشورات بعد",
  "joinForum": "انضمام",
  "writePost": "اكتب المحتوى...",
  "postTitle": "عنوان المنشور",
  "fillPostFields": "يرجى تعبئة العنوان والمحتوى",
  "createForum": "إنشاء منتدى",
  "forumName": "اسم المنتدى",
  "forumNameHint": "مثال: نصائح التغذية",
  "forumDescription": "الوصف (اختياري)",
  "forumNameRequired": "اسم المنتدى مطلوب",
  "forumCreated": "تم إنشاء المنتدى بنجاح",

  // consultations
  "consultations": "الاستشارات",
  "consultationsDesc": "حجز استشارات مع الأطباء",
  "noConsultations": "لا توجد استشارات",
  "requestConsultation": "طلب استشارة",
  "doctorId": "معرف الطبيب",
  "consultationType": "نوع الاستشارة",
  "initialConsultation": "استشارة أولية",
  "followUp": "متابعة",
  "review": "مراجعة",
  "scheduledDate": "التاريخ والوقت",
  "request": "طلب",
  "cancel": "إلغاء",

  // diet
  "myDiet": "حميتي",
  "myDietDesc": "عرض خطة الحمية والوجبات الحالية",
  "subscribedFeatures": "مميزات المشتركين",
  "noDiet": "لايوجد اي حميات بعد",
  "dietMeals": "وجبات الحمية",
  "viewMeals": "عرض الوجبات",
  "tapToViewDiet": "اضغط لعرض تفاصيل الحمية",
  "dietContents": "محتوى الحمية",
  "noMealsInPlan": "لا توجد وجبات في هذه الخطة",
  "day": "اليوم",
  "notes": "ملاحظات",
  "noMeals": "لا توجد وجبات",
  "createDietPlan": "إنشاء خطة حمية",
  "dietPeriods": "فترات الحمية",
  "breakfast": "وجبة الافطار",
  "lunch": "وجبة الغداء",
  "dinner": "وجبة العشاء",
  "firstSnack": "السناك الاول",
  "secondSnack": "السناك الثاني",
  "thirdSnack": "السناك الثالث",
  "addAnotherPeriod": "أضف فترة زمنية أخرى",
  "nextStep": "الانتقال للخطوة التالية",
  "addSnack": "أضف سناك",
  "extraSnack": "سناك إضافي",
  "setTimeForEachMeal": "حدد الوقت لكل وجبة وسناك",
  "savedMealTimes": "أوقات الوجبات المحفوظة",
  "patientId": "معرف المريض",
  "dietPlanTitle": "عنوان الخطة",
  "dietPlanTitleHint": "مثال: خطة خسارة الوزن",
  "dietPlanFor": "خطة حمية لـ @name",
  "dailyCalories": "السعرات اليومية",
  "durationDays": "المدة (بالأيام)",
  "startDate": "تاريخ البدء",
  "endDate": "تاريخ الانتهاء",
  "startDateHint": "2024-01-01",
  "endDateHint": "2024-01-31",
  "create": "إنشاء",
  "you": "أنت",
  "saved": "تم الحفظ بنجاح",
  "remove": "إزالة",
  "nutritionMacros": "التغذية (كربوهيدرات، دهون، بروتين)",
  "carbohydrates": "الكربوهيدرات",
  "fats": "الدهون",
  "protein": "البروتين",
  "createDietForPatient": "إنشاء حمية للمريض",
  "dietTargets": "أهداف الحمية",
  "baseServings": "الحصص الأساسية",
  "baseServingsDesc": "حدد الحصص وقيم الكربوهيدرات والبروتين والدهون (غ) لكل مجموعة",
  "baseServingsExceedsTargetWarning": "مجموع الحصص الأساسية يتجاوز أهداف المريض. القيم المتبقية قد تكون صفراً. يمكنك المتابعة.",
  "contributionFromBaseServings": "المساهمة من الحصص الأساسية المختارة",
  "remainingRequirements": "المتبقي من الاحتياجات",
  "fruitsContribution": "مساهمة الفواكه",
  "vegetablesContribution": "مساهمة الخضروات",
  "milkContribution": "مساهمة الحليب",
  "totalContribution": "المساهمة الإجمالية",
  "remainingCarbs": "الكربوهيدرات المتبقية",
  "remainingProtein": "البروتين المتبقي",
  "remainingFat": "الدهون المتبقية",
  "remainingCalories": "السعرات المتبقية",
  "dietDistribution": "توزيع الحصص",
  "group": "المجموعة",
  "tdee": "TDEE",
  "targetCalories": "السعرات المستهدفة",
  "goal": "الهدف",
  "maintain": "المحافظة",
  "weightLoss": "خسارة الوزن",
  "weightGain": "زيادة الوزن",
  "starch": "خبزيات",
  "fruit": "فواكه",
  "vegetables": "خضروات",
  "milk": "حليب",
  "meat": "لحوم/بروتين",
  "fat": "دهون",
  "servingsPerDay": "حصص/يوم",
  "determineServingsPerMeal": "تحديد الحصص للوجبات",
  "totalDaily": "المجموع اليومي",
  "servings": "حصص",
  "milkSkim": "حليب خالي الدسم",
  "milkLowFat": "حليب قليل الدسم",
  "milkWhole": "حليب كامل الدسم",
  "meatVeryLean": "لحم قليل الدهون جداً",
  "meatLean": "لحم قليل الدهون",
  "meatMediumFat": "لحم متوسط الدهون",
  "meatHighFat": "لحم عالي الدهون",
  "fillPatientProfile": "يرجى إكمال بيانات المريض (الطول، الوزن، تاريخ الميلاد)",
  "dietPortionCategories": "تحديد الحصص للوجبات",
  "mainCategories": "الفئات الرئيسية",
  "numberOfPortions": "عدد الحصص",
  "fatsG": "الدهون (و)",
  "calculateAndShowRemaining": "حساب الناتج وإظهار بقية البيانات",
  "proceedToNextStep": "انتقل للخطوة التالية",
  "otherCarbs": "كربوهيدرات أخرى",
  "carbDistribution": "تقسيم حصص الكربوهيدرات",
  "proteinDistribution": "تقسيم حصص اللحوم (البروتينات)",
  "totalCarbPortions": "حصص الكربوهيدرات الكلية الناتجة",
  "totalProteinPortions": "حصص البروتينات الكلية الناتجة",
  "totalFatPortions": "حصص الدهون الكلية الناتجة",
  "fatDistribution": "ناتج مجموع الدهون",
  "divideAmongFields": "قم بتقسيمها على الحقول التالية",
  "starchPortions": "حصص النشويات",
  "otherCarbPortions": "حصص الكربوهيدرات الأخرى",
  "veryLeanMeatPortions": "حصص اللحوم قليلة الدهون جدا",
  "leanMeatPortions": "حصص اللحوم قليلة الدهون",
  "mediumFatMeatPortions": "حصص اللحوم متوسطة الدهون",
  "highFatMeatPortions": "حصص اللحوم عالية الدهون",
  "portionDistributionByPeriods": "تقسيم الحصص على الفترات",
  "selectedPortions": "الحصص المختارة",
  "proceedToLastStep": "الانتقال للخطوة الاخيرة",
  "determineMeals": "تحديد الوجبات",
  "enterMealsFor": "ادخل الوجبات لـ",
  "enterNotesIfAny": "ادخل ملاحظاتك ان وجدت",
  "createDiet": "انشاء الحمية",
// subscribe flow
  "subscriptionInfo": "معلومات الاشتراك",
  "enterYourInfo": "ادخل معلوماتك",
  "fullName": "الاسم الكامل",
  "selectDateOfBirth": "اختر تاريخ الميلاد",
  "selectHeight": "اختر الطول",
  "selectWeight": "اختر الوزن",
  "activitySedentaryLong": "عديم الحركة تعمل مكتبي واستخدام السيارات.",
  "activityLightLong": "قليل الحركة كالقايم باعمال منزلية خفيفة فقط",
  "activityModerateLong": "متوسط الحركة كالقيام باعمال منزلي و المشي او بعض التمارين",
  "activityActiveLong": "نشيط كالقيام بالتمارين كل 3 ايام بالأسبوع",
  "paymentInvoice": "فاتورة الدفع",
  "doctorNameLabel": "اسم الطبيب",
   "attachPaymentInvoice": "ارفاق فاتورة الدفع",
  "next": "التالي",
  "meatTargetPortions": "حصص اللحوم المتبقية",
  "starchTargetPortions": "حصص النشويات المتبقية",
  "fatTargetPortions": "حصص الدهون المتبقية",
  "calculateTargets": "احسب الحصص",
  "dietFinalSummary": "ملخص التوزيع النهائي",
  "back": "رجوع",
  "finish": "إنهاء",
  "targetProtein": "البروتين المستهدف",
  "targetCarbs": "الكربوهيدرات المستهدفة",
  "targetFat": "الدهون المستهدفة",
  "viewDietChoice": "عرض الحميات السابقة",
  "createDietChoice": "إنشاء حمية جديدة",
  "editDietChoice": "تعديل الحمية",
  "dietHistory": "سجل الحميات المخصصة",
};
