const Map<String, String> enTranslation = {
  "appName": "Nutri Guide",
  "welcome": "Welcome",
  "welcomeTitle": "Welcome",
  "welcomeBody": "Here we offer you guidance and tips about healthy diets to help you achieve your health goals.",
  "exit": "Exit",
  "language": "Language",
  "splash": "wait...",
  "login": "Login",
  "enterUserName": "Enter User Name",
  "username": "UserName",
  "hintPassword": "Enter Password",
  "password": "Password",
  "dont_have_account": "don`t have account",
  "dontHaveAccountQuestion": "Don't have an account? ",
  "createAccountAction": "Create an account",
  "enterPersonalEmail": "Enter personal email",
  "alreadyHaveAccountQuestion": "Already have an account? ",
  "loginAction": "Sign in",
  "asUser": "As a user",
  "asDoctor": "Enter as Doctor",
  "permissionRequired": "Permission Required",
  "exactAlarmPermissionDescription": "To ensure the alarm rings on time, we need exact alarm permission. Please enable it in settings.",
  "enterNameShort": "Enter name",
  "confirmPasswordAction": "Confirm password",
  "enterDietPrice": "Enter diet price",
  "enterBankAccount": "Enter bank account",
  "academicDegree": "Academic degree",
  "cvBio": "CV / Biography",
  "signup": "signup",
  "forget_password": "forget password",
  'forgotPasswordTitle': 'Forgot Password',
  'verifyEmailTitle': 'Verify Email',
  'verificationCode': 'Verification Code',
  'verificationCodeSentTo': 'Verification code has been sent to',
  'verify': 'Verify',
  'goBack': 'Go back',
  'verifyCodeRequired': 'Please enter the verification code',
  'verifyFailed': 'Verification failed',
  'emailVerified': 'Email verified successfully',
  'verificationCodeResent': 'Verification code has been resent to your email',
  'resendCode': 'Resend code',
  'email': 'Email',
  'enterYourEmail': 'Enter your email',
  'sendResetLink': 'Send reset link',
  'pleaseWait': 'Please wait...',
  // signup
  'signupTitle': 'Sign Up',
  'signupButton': 'Sign Up',

  // fields
  'name': 'Name',
  'enterName': 'Enter your name',
  'enterEmail': 'Enter your email',
  'phoneOptional': 'Phone (optional)',
  'enterPhone': 'Enter phone number',


  'passwordHint': 'Min 8 characters',
  'confirmPassword': 'Confirm Password',
  'confirmPasswordHint': 'Re-enter password',

  // role
  'roleOptional': 'Role (optional)',
  'selectRole': 'Select role',
  'patient': 'Patient',
  'doctor': 'Doctor',

  "homeTitle": "Home",
  "settings": "Settings",
  "personalAccount": "Personal Account",
  "remindersAlerts": "Reminders and Alerts",
  "team": "Team",
  "editProfile": "Edit Profile",
  "enterPassword": "Enter Password",
  "addReminder": "Add Reminder",
  "reminderTime": "Reminder time",
  "save": "Save",
  "close": "Close",
  "send": "Send",
  "medicalTest": "Medical Test",
  "enterTestName": "Enter test name",
  "selectFile": "Please select a file",
  "tapToUpload": "Tap to upload",
  "personalPatientInfo": "Personal Patient Information",
  "editPersonalInfo": "Edit personal info",
  "diets": "Diets",
  "dietsPatientsTitle": "Diets · Patients",
  "chat": "Chat",
  "chatWithPatients": "Chat with patients",
  "reports": "Reports",
  "bodyCalculations": "Body Calculations",
  "specialistDoctorInfo": "Specialist doctor info",
  "goToYourForums": "Go to your nutrition forum",
  "showBodyCalculations": "View body calculations",
  "saveCalculation": "Save calculation",
  "tapToViewDetails": "Tap to view details",
  "calculation": "Calculation",
  "noCalculationsYet": "No calculations yet. Do a calculation from the drawer and save it.",
  "totalKcal": "Total daily kcal",
  "medicalExaminations": "Medical Examinations",
  "helpFiles": "Help Files",
  "helpFileJurd": "Jordanian book",
  "helpFileKrause": "Krause reference",
  "helpFileAlter": "Exchange list system",
  "mainMenu": "Main Menu",
  "edit": "Edit",
  "delete": "Delete",
  "noReminders": "No reminders yet. Tap Add Reminder to create one.",
  "myClinic": "My Clinic",
  "stepCounter": "Step Counter",
  "startCounting": "Start Counting",
  "step": "step",
  "steps": "steps",
  "stepCounterPermissionDenied": "Activity tracking permission is required to count steps",
  "spiritualNutrition": "Spiritual Nutrition",
  "morningAthkar": "Morning Supplications",
  "eveningAthkar": "Evening Supplications",
  "athkar": "Supplications",
  "noAthkarFound": "No supplications found",
  "comingSoon": "Coming soon",
  "tooManyRequests": "Too many requests. Please wait a minute and try again.",
  "download": "Download",
  "openFile": "Open",
  "downloadFailed": "Download failed",
  "downloadFailedTryBrowser": "If the backend serves files via URL, you can try opening in browser:",
  "downloading": "Downloading...",
  "downloadSuccess": "Download successful",
  "fileDownloadedTo": "The file has been downloaded to the path",
  "noHelpFiles": "No help files available",
  "noMedicalTests": "No medical tests",
  "noPatients": "No patients",
  "selectPatient": "Select a patient to view their medical tests",
  "doctorsList": "Doctors List",
  "doctorsListDesc": "Browse available doctors",
  "tips": "Tips",
  "tipsDesc": "Health tips and guidance",
  "tipsIntro": "Many medical nutritional tips useful for you!",
  "tipsGeneral": "General nutritional tips",
  "tipsSports": "Sports tips",
  "tipsMyths": "Nutritional myths",
  "noTipsFound": "No tips found",
  "adDetails": "Advertisement",
  "adDescription": "Description",
  "openLink": "Open link",
  "callNow": "Call",
  "bmiCalc": "BMI Calculator",
  "bmiCalcDesc": "Calculate your BMI quickly",
  "phone": "Phone",
  "role": "Role",
  "logout": "Logout",
  "yourPrivateClinic": "Your Private Clinic",
  "welcomeToClinic": "Welcome",
  "welcomeToClinicSub": "to your virtual clinic",
  "welcomeToDoctorVirtualClinic": "Welcome to Dr. @name's clinic",
  "patientsList": "Patients List",
  "searchForPatient": "Search for your patient",
  "patientInformation": "Patient Information",
  "nutritionalCalculations": "Nutritional Calculations",
  "proteinFatCarbs": "Protein, Fat, and Carbohydrate Ratios",
  "patientName": "Patient Name",
  "patientAge": "Patient Age",
  "patientGender": "Patient Gender",
  "patientPhone": "Patient Phone",
  "saveChanges": "Save Changes",
  "servingsInGrams": "Number of servings in grams",
  "macroPercent": "Percentage",
  "totalCalories": "Total calories",
  "macroSumMustBe100": "Sum of percentages must equal 100%",
  "physicalActivityLevel": "Physical Activity",
  "calories": "Calories",
  "bmr": "BMR",
  "noInternet": "No internet connection",
  "serverError": "Server error",
  "retry": "Retry",
  "refresh": "Refresh",
  "noDoctors": "No doctors found",
  "available": "Available",
  "notAvailable": "Not available",
  "verified": "Verified",
  "notVerified": "Not verified",
  "rating": "Rating",
  "rateDoctor": "Rate this doctor",
  "yourRating": "Your rating",
  "noRateYet": "No rate yet — tap stars to rate",
  "noRatesYet": "No rates yet",
  "sendRate": "Send rate",
  "reviews": "reviews",
  "noReviews": "No reviews yet",
  "ratingSaved": "Rating saved",
  "experience": "Experience",
  "years": "years",
  "fee": "Fee",
  "heightCm": "Height (cm)",
  "heightHint": "Enter height in cm",
  "weightKg": "Weight (kg)",
  "weightHint": "Enter weight in kg",
  "calculate": "Calculate",
  "bmiResult": "Your BMI",
  "bmiUnder": "Underweight",
  "bmiNormal": "Normal weight",
  "bmiOver": "Overweight",
  "bmiObese": "Obese",
  "error": "Error",
  "enterHeightWeight": "Please enter height and weight",
  "invalidValues": "Invalid values",
  "invalidAge": "Please enter a logical age (less than 100)",
  "invalidWeight": "Please enter a logical weight (less than 200 kg)",
  "invalidHeight": "Please enter a logical height (between 50 and 250 cm)",
  "doctorDetails": "Doctor Details",
  "personalEmail": "Personal Email",
  "bankAccount": "Bank Account",
  "dietPrice": "Diet Price",
  "choosePlan": "Choose a plan",
  "basicPlan": "Basic",
  "premiumPlan": "Premium",
  "months": "months",
  "subscribe": "Subscribe",

  "gender": "Gender",
  "degree": "Degree",
  "specialization": "Specialization",
  "license": "License number",
  "consultationFee": "Consultation fee",
  "yearsOfExperience": "Years of Experience",
  "bio": "Professional Bio",

  "success": "Success",
  "ok": "OK",
  "sessionExpired": "Session expired, please login again",
  "subscribeFailed": "Subscription failed, try again",
  "subscriptionCreated": "Subscription created successfully",
  "subscriptionPending": "Subscription Pending Approval",
  "subscriptionPendingDesc": "Invoice received. The 'My Diet' section will appear here once approved by admin.",
  "virtual_payment": "Virtual Payment",
  "payment_card": "Card",
  "payment_cash": "Cash",
  "payment_wallet": "Wallet",
  "summary_plan": "Plan",
  "summary_duration": "Duration",
  "summary_price": "Price",
  "pay_and_subscribe": "Pay & Subscribe",

  "payment_transfer": "Transfer",

// Card
  "card_info": "Card Information",
  "card_holder": "Card Holder Name",
  "card_holder_hint": "Name on the card",
  "card_number": "Card Number",
  "card_number_hint": "**** **** **** ****",
  "card_exp": "Expiry Date",
  "card_exp_hint": "MM/YY",
  "card_cvv": "CVV",
  "card_cvv_hint": "***",

// Wallet
  "wallet_info": "Wallet Information",
  "wallet_name": "Wallet Name",
  "wallet_name_hint": "e.g. YemenPay",
  "wallet_number": "Wallet Number",
  "wallet_number_hint": "Phone or account number",
  "wallet_ref": "Transaction Reference",
  "wallet_ref_hint": "Transaction ID or reference",

// Transfer
  "transfer_info": "Transfer Information",
  "transfer_sender": "Sender Name",
  "transfer_sender_hint": "Sender full name",
  "transfer_receiver": "Receiver Name",
  "transfer_receiver_hint": "Receiver full name",
  "transfer_ref": "Transfer Reference",
  "transfer_ref_hint": "Transfer ID or reference",
  "transfer_amount": "Transfer Amount",
  "transfer_amount_hint": "Enter amount",
  "login_failed": "Login Failed",
  "accountPendingApproval": "Your account is pending admin approval.",
  "accountPendingApprovalHint": "The app allows doctors to sign in before approval. Your server must return a token for pending doctors (e.g. when the app sends allow_pending_doctor: true in the login request). Ask your administrator to enable this.",
  "male":"male",
  "female":"female",
  "results":"results",
  "age":"age",
  "bmiBmrCalc": "Clinical BMI & BMR Calc",
  "enterData": "Enter Bio-Data",

  "kcalPerDay": "kcal/day",

  // Input Fields

  "ageHint": "ex: 25",


  // Activity Levels (As per sheet)
  "activityLevel": "Physical Activity Level",
  "activitySedentary": "Sedentary (No activity)",
  "activityLow": "Low Active",
  "activityModerate": "Moderate Active",
  "activityVery": "Very Active",
  "activityExtra": "Extra Active",


  "bmiObese1": "Obese Class I",
  "bmiObese2": "Obese Class II",
  "bmiObese3": "Morbid Obesity",

  // Alerts
  "enterAllFields": "Please fill all fields",


  "completeProfile": "Complete your profile",

  "dateOfBirth": "Date of birth",

  "physicalActivity": "Physical activity",
  "sedentary": "Sedentary",
  "low": "Low",
  "active": "Active",
  "veryActive": "Very Active",
  "medicalHistory": "Medical history",
  "profileSaved": "Profile saved successfully",
  "fillFields": "Please fill required fields correctly",

  // forums
  "forums": "Forums",
  "forumsDesc": "Join discussions with others",
  "noForums": "No forums found",
  "forumPosts": "Posts",
  "noPosts": "No posts yet",
  "joinForum": "Join",
  "writePost": "Write your content...",
  "postTitle": "Post title",
  "fillPostFields": "Please fill title and content",
  "createForum": "Create forum",
  "forumName": "Forum name",
  "forumNameHint": "e.g. Nutrition tips",
  "forumDescription": "Description (optional)",
  "forumNameRequired": "Forum name is required",
  "forumCreated": "Forum created successfully",

  // consultations
  "consultations": "Consultations",
  "consultationsDesc": "Schedule consultations with doctors",
  "noConsultations": "No consultations found",
  "requestConsultation": "Request Consultation",
  "doctorId": "Doctor ID",
  "consultationType": "Consultation Type",
  "initialConsultation": "Initial Consultation",
  "followUp": "Follow-up",
  "review": "Review",
  "scheduledDate": "Scheduled Date",
  "request": "Request",
  "cancel": "Cancel",

  // diet
  "myDiet": "My Diet",
  "myDietDesc": "View your current diet plan and meals",
  "subscribedFeatures": "Subscriber benefits",
  "noDiet": "No diets yet",
  "dietMeals": "Diet Meals",
  "viewMeals": "View Meals",
  "tapToViewDiet": "Tap to view diet details",
  "dietContents": "Diet Contents",
  "noMealsInPlan": "No meals in this plan",
  "day": "Day",
  "notes": "Notes",
  "noMeals": "No meals found",
  "createDietPlan": "Create Diet Plan",
  "dietPeriods": "Diet Periods",
  "breakfast": "Breakfast",
  "lunch": "Lunch",
  "dinner": "Dinner",
  "firstSnack": "First Snack",
  "secondSnack": "Second Snack",
  "thirdSnack": "Third Snack",
  "addAnotherPeriod": "Add another time period",
  "nextStep": "Move to next step",
  "addSnack": "Add snack",
  "extraSnack": "Extra Snack",
  "setTimeForEachMeal": "Set time for each meal and snack",
  "savedMealTimes": "Saved meal times",
  "patientId": "Patient ID",
  "dietPlanTitle": "Plan Title",
  "dietPlanTitleHint": "e.g. Weight loss plan",
  "dietPlanFor": "Diet plan for @name",
  "dailyCalories": "Daily Calories",
  "durationDays": "Duration (Days)",
  "startDate": "Start Date",
  "endDate": "End Date",
  "startDateHint": "2024-01-01",
  "endDateHint": "2024-01-31",
  "create": "Create",
  "you": "You",
  "saved": "Saved successfully",
  "remove": "Remove",
  "nutritionMacros": "Nutrition (Carbs, Fats, Protein)",
  "carbohydrates": "Carbohydrates",
  "fats": "Fats",
  "protein": "Protein",
  "createDietForPatient": "Create diet for patient",
  "dietTargets": "Diet Targets",
  "baseServings": "Base Servings",
  "baseServingsDesc": "Set servings and enter carbs, protein, and fat (g) for each group",
  "baseServingsExceedsTargetWarning": "Base group totals exceed patient targets. Remaining values may be zero. You can still proceed.",
  "contributionFromBaseServings": "Contribution from selected base servings",
  "remainingRequirements": "Remaining requirements",
  "fruitsContribution": "Fruits contribution",
  "vegetablesContribution": "Vegetables contribution",
  "milkContribution": "Milk contribution",
  "totalContribution": "Total contribution",
  "remainingCarbs": "Remaining carbs",
  "remainingProtein": "Remaining protein",
  "remainingFat": "Remaining fat",
  "remainingCalories": "Remaining calories",
  "dietDistribution": "Meal Distribution",
  "group": "Group",
  "tdee": "TDEE",
  "targetCalories": "Target Calories",
  "goal": "Goal",
  "maintain": "Maintain",
  "weightLoss": "Weight Loss",
  "weightGain": "Weight Gain",
  "starch": "Starch",
  "fruit": "Fruit",
  "vegetables": "Vegetables",
  "milk": "Milk",
  "meat": "Meat/Protein",
  "fat": "Fat",
  "servingsPerDay": "Servings/day",
  "determineServingsPerMeal": "Determine servings per meal",
  "totalDaily": "Total Daily",
  "servings": "Servings",
  "milkSkim": "Skim milk",
  "milkLowFat": "Low-fat milk",
  "milkWhole": "Whole milk",
  "meatVeryLean": "Very lean meat",
  "meatLean": "Lean meat",
  "meatMediumFat": "Medium-fat meat",
  "meatHighFat": "High-fat meat",
  "fillPatientProfile": "Please complete patient profile (height, weight, birthdate)",
  "dietPortionCategories": "Determine portions for meals",
  "mainCategories": "Main Categories",
  "numberOfPortions": "Number of Portions",
  "fatsG": "Fats (g)",
  "calculateAndShowRemaining": "Calculate result and show remaining data",
  "proceedToNextStep": "Proceed to next step",
  "otherCarbs": "Other carbohydrates",
  "carbDistribution": "Carbohydrate portion distribution",
  "proteinDistribution": "Dividing meat portions (Proteins)",
  "totalCarbPortions": "Total carbohydrate portions resulting",
  "totalProteinPortions": "Total protein portions resulting",
  "totalFatPortions": "Total fat portions resulting",
  "fatDistribution": "Total fat result",
  "divideAmongFields": "Divide them among the following fields",
  "starchPortions": "Starch portions",
  "otherCarbPortions": "Other carbohydrate portions",
  "veryLeanMeatPortions": "Very low-fat meat portions",
  "leanMeatPortions": "Low-fat meat portions",
  "mediumFatMeatPortions": "Medium-fat meat portions",
  "highFatMeatPortions": "High-fat meat portions",
  "portionDistributionByPeriods": "Portion distribution by periods",
  "selectedPortions": "Selected Portions",
  "proceedToLastStep": "Proceed to the last step",
  "determineMeals": "Determine Meals",
  "enterMealsFor": "Enter meals for",
  "enterNotesIfAny": "Enter your notes if any",
  "createDiet": "Create Diet",

  // subscribe flow
  "subscriptionInfo": "Subscription Information",
  "enterYourInfo": "Enter your information",
  "fullName": "Full name",
  "selectDateOfBirth": "Select date of birth",
  "selectHeight": "Select height",
  "selectWeight": "Select weight",
  "activitySedentaryLong": "Sedentary: office work and car use.",
  "activityLightLong": "Lightly active: light household chores only.",
  "activityModerateLong": "Moderately active: household chores, walking or some exercise.",
  "activityActiveLong": "Active: exercise about 3 days per week.",
  "paymentInvoice": "Payment Invoice",
  "doctorNameLabel": "Doctor name",
   "attachPaymentInvoice": "Attach payment invoice",
  "next": "Next",
  "meatTargetPortions": "Remaining Meat Portions",
  "starchTargetPortions": "Remaining Starch Portions",
  "fatTargetPortions": "Remaining Fat Portions",
  "calculateTargets": "Calculate Portions",
  "dietFinalSummary": "Final Distribution Summary",
  "back": "Back",
  "finish": "Finish",
  "targetProtein": "Target Protein",
  "targetCarbs": "Target Carbs",
  "targetFat": "Target Fat",
  "dietErrorRate": "Diet Error Rate",
};


